app:
  build: .
  dockerfile: Dockerfile-Go
  links:
    - db
  environment:
    - DB_USER=root
    - DB_PASSWORD=root
    - DB_HOST=db
  ports:
    - "4000:4000"
db:
  build: .
  dockerfile: Dockerfile-MySQL
  volumes:
    - ./db/mysql_data:/var/lib/mysql
    - ./db/init:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=user
  command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci
